nexora:
  redis:
    enabled: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration

  datasource:
    url: jdbc:h2:mem:nexora_test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false

  sql:
    init:
      mode: always
      schema-locations: classpath:db/test-schema.sql

logging:
  level:
    com.nexora: INFO
    org.springframework.security: DEBUG
