spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexora?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: http://localhost:9200

rocketmq:
  name-server: localhost:9876
  producer:
    group: nexora-producer-group

nexora:
  elasticsearch:
    enabled: true

logging:
  level:
    com.nexora: DEBUG
    org.springframework: INFO
