apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexora-backend
  namespace: nexora
  labels:
    app: nexora-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nexora-backend
  template:
    metadata:
      labels:
        app: nexora-backend
    spec:
      containers:
        - name: nexora-backend
          image: crpi-27zlqugq2208c0pz.cn-hangzhou.personal.cr.aliyuncs.com/xiaofeiyang930112/nexora-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: nexora-config
            - secretRef:
                name: nexora-secrets
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: nexora-config
                  key: JAVA_OPTS
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
