apiVersion: v1
kind: ConfigMap
metadata:
  name: nexora-config
  namespace: nexora
data:
  SPRING_PROFILES_ACTIVE: "prod"
  REDIS_HOST: "nexora-redis"
  REDIS_PORT: "6379"
  ES_ENABLED: "true"
  LLM_BASE_URL: "https://api.deepseek.com"
  LLM_MODEL: "deepseek-v4-pro"
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC"
