apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexora-ingress
  namespace: nexora
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: nexora-redirect-https@kubernetescrd
spec:
  rules:
    - host: nexora.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nexora-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexora-frontend
                port:
                  number: 80
