apiVersion: v1
kind: Secret
metadata:
  name: nexora-secrets
  namespace: nexora
type: Opaque
stringData:
  # 数据库
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  DB_URL: "jdbc:mysql://nexora-mysql:3306/nexora?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
  # Redis
  REDIS_PASSWORD: ""
  # LLM
  LLM_API_KEY: "${LLM_API_KEY}"
  # RocketMQ
  ROCKETMQ_NAMESRV: "nexora-rmq-namesrv:9876"
